Repository janeljs/issue-tracker, pull requests merged in 2021-07, with the labels that each got.

#125 [FE] 0701 작업
  frontend/src/App.js
  frontend/src/components/common/tabModal/ModalContentList.tsx
  frontend/src/page/detailIssuePage/detailHeader/DetailIssueHeader.tsx
  frontend/src/page/detailIssuePage/detailHeader/HeaderEditMode.tsx
  frontend/src/page/loginPage/LoginPage.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterModal.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/SearchInput.tsx
  frontend/src/store/loginStore.ts
Labels: FE

#127 [FE] 로그아웃 기능 구현
  frontend/src/components/header/Header.tsx
Labels: FE, enhancement

#130 [FE] FIX: POST 후에 업데이트된 데이터 받아오도록 수정
  frontend/src/page/detailIssuePage/commentList/CommentList.tsx
  frontend/src/page/detailIssuePage/commentList/EditComment.tsx
  frontend/src/page/labelPage/labelEditForm/LabelEditForm.tsx
  frontend/src/page/labelPage/labelTable/LabelItem.tsx
  frontend/src/page/milestonePage/MilestoneEditForm.tsx
  frontend/src/page/milestonePage/milestoneTable/MilestoneInfo.tsx
Labels: FE, bug

#132 [FE] 로그아웃 서버 요청 및 JWT 만료시 에러처리 진행 중
  frontend/src/App.js
  frontend/src/components/common/LabelMilestoneTab.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/page/mainPage/issueTable/IssueTable.tsx
  frontend/src/store/issueInfoStore.ts
  frontend/src/util/api/api.ts
  frontend/src/util/api/apiType.ts
  frontend/src/util/api/fetchIssueDetail.ts
  frontend/src/util/api/fetchLogin.ts
Labels: FE, enhancement

#134 Feat: 필터 클리어 버튼 , 마일스톤 날짜 입력 양식체크,/ Fix: 마일스톤 날짜,설명 에러 수정
  frontend/src/components/atom/InputField.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/page/loginPage/loginLogo/LoginLogo.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeaderLeft.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilter.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterClear.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterModal.tsx
  frontend/src/page/milestonePage/MilestoneEditForm.tsx
  frontend/src/util/api/api.ts
  frontend/src/util/api/apiType.ts
  frontend/src/util/api/fetchLogin.ts
Labels: FE, enhancement

#136 [FE]페이지 작업
  frontend/src/components/atom/Pagination.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/page/mainPage/issueTable/IssueTable.tsx
  frontend/src/store/issueInfoStore.ts
Labels: FE, enhancement

#137 테스트 코드 추가
  BE/build.gradle
  BE/src/main/java/com/issuetracker/domain/elasticsearch/IssueDocumentRepository.java
  BE/src/main/java/com/issuetracker/web/dto/reqeust/IssueRequestDTO.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/image/test-image.png
  BE/src/test/java/com/issuetracker/service/BaseServiceTest.java
  BE/src/test/java/com/issuetracker/service/ImageServiceTest.java
  BE/src/test/java/com/issuetracker/service/IssueCommandServiceTest.java
  BE/src/test/java/com/issuetracker/service/IssueQueryServiceTest.java
  BE/src/test/java/com/issuetracker/service/LabelServiceTest.java
  BE/src/test/java/com/issuetracker/service/MilestoneServiceTest.java
Labels: BE

#138 Fe/check
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Portal.js
  frontend/src/components/atom/LoadingProgress.tsx
  frontend/src/components/atom/Pagination.tsx
  frontend/src/components/common/Copyright.tsx
  frontend/src/components/common/ErrorBoundary.jsx
  frontend/src/components/common/LabelMilestoneTab.tsx
  frontend/src/page/createIssuePage/CreateIssuePage.tsx
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/page/detailIssuePage/commentList/Comment.tsx
  frontend/src/page/detailIssuePage/commentList/CommentInput.tsx
  frontend/src/page/detailIssuePage/commentList/CommentList.tsx
  frontend/src/page/detailIssuePage/detailHeader/DetailIssueHeader.tsx
  frontend/src/page/detailIssuePage/detailHeader/HeaderEditMode.tsx
  frontend/src/page/detailIssuePage/detailHeader/HeaderViewMode.tsx
  frontend/src/page/detailIssuePage/detailIssueOption/DetailIssueOption.tsx
  frontend/src/page/errorPage/ErrorPage.tsx
  frontend/src/page/labelPage/LabelPage.tsx
  frontend/src/page/loginPage/socialLoginBtn/SocialLoginBtn.tsx
  frontend/src/page/mainPage/MainPage.tsx
  frontend/src/page/mainPage/issueTable/IssueItem.tsx
  frontend/src/page/mainPage/issueTable/IssueTable.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeaderLeft.tsx
  frontend/src/page/mainPage/optionTable/OptionTable.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterModal.tsx
  frontend/src/page/milestonePage/MilestoneEditForm.tsx
  frontend/src/page/milestonePage/MilestonePage.tsx
  frontend/src/page/milestonePage/milestoneTable/MilestoneInfo.tsx
  frontend/src/page/milestonePage/milestoneTable/MilestoneTable.tsx
  frontend/src/store/issueInfoStore.ts
  frontend/src/store/labelMilestoneStore.ts
  frontend/src/store/labelMilestoneTabStore.ts
  frontend/src/store/milestoneStore.ts
  frontend/src/util/ImgParser.ts
  frontend/src/util/api/api.ts
  frontend/src/util/api/apiType.ts
  frontend/src/util/api/fetchHandleMilestone.ts
  frontend/src/util/api/fetchIssueDetail.ts
  frontend/src/util/api/fetchLogin.ts
Labels: FE

#142 [BE] 컨트롤러 테스트 코드 추가
  BE/src/test/java/com/issuetracker/service/IssueQueryServiceTest.java
  BE/src/test/java/com/issuetracker/web/BaseControllerTest.java
  BE/src/test/java/com/issuetracker/web/ImageControllerTest.java
  BE/src/test/java/com/issuetracker/web/IssueControllerTest.java
  BE/src/test/java/com/issuetracker/web/LabelControllerTest.java
  BE/src/test/java/com/issuetracker/web/MilestoneControllerTest.java
Labels: BE
