Repository janeljs/issue-tracker, pull requests merged in 2021-06, with the labels that each got.

#20 [BE] OAuth 로그인, 로그아웃 구현
  build.gradle
  src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
  src/main/java/com/jane_eno/issue_tracker/auth/JwtAuthInterceptor.java
  src/main/java/com/jane_eno/issue_tracker/auth/OAuth.java
  src/main/java/com/jane_eno/issue_tracker/auth/UserNameArgumentResolver.java
  src/main/java/com/jane_eno/issue_tracker/auth/annotation/LoginRequired.java
  src/main/java/com/jane_eno/issue_tracker/auth/annotation/UserName.java
  src/main/java/com/jane_eno/issue_tracker/auth/dto/AccessTokenRequestDTO.java
  src/main/java/com/jane_eno/issue_tracker/auth/dto/AccessTokenResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/auth/dto/GitHubUserResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/auth/exception/AccessTokenNotFoundException.java
  src/main/java/com/jane_eno/issue_tracker/auth/exception/ErrorMessage.java
  src/main/java/com/jane_eno/issue_tracker/auth/exception/GitHubUserNotFoundException.java
  src/main/java/com/jane_eno/issue_tracker/auth/exception/HttpProtocolViolationException.java
  src/main/java/com/jane_eno/issue_tracker/auth/exception/IllegalHostException.java
  src/main/java/com/jane_eno/issue_tracker/auth/exception/OAuthException.java
  src/main/java/com/jane_eno/issue_tracker/auth/util/GitHubUtil.java
  src/main/java/com/jane_eno/issue_tracker/auth/util/Host.java
  src/main/java/com/jane_eno/issue_tracker/auth/util/JwtUtil.java
  src/main/java/com/jane_eno/issue_tracker/config/WebConfig.java
  src/main/java/com/jane_eno/issue_tracker/domain/user/User.java
  src/main/java/com/jane_eno/issue_tracker/domain/user/UserRepository.java
  src/main/java/com/jane_eno/issue_tracker/exception/EntityNotFoundException.java
  src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
  src/main/java/com/jane_eno/issue_tracker/service/UserService.java
  src/main/java/com/jane_eno/issue_tracker/web/UserController.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/UserResponseDTO.java
Labels: BE

#29 [BE] 엔티티 관계 맵핑
  src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
  src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
  src/main/java/com/jane_eno/issue_tracker/domain/label/Color.java
  src/main/java/com/jane_eno/issue_tracker/domain/label/Label.java
  src/main/java/com/jane_eno/issue_tracker/domain/milestone/Milestone.java
  src/main/java/com/jane_eno/issue_tracker/domain/milestone/MilestoneRepository.java
  src/main/java/com/jane_eno/issue_tracker/domain/user/User.java
  src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
  src/main/java/com/jane_eno/issue_tracker/service/LabelService.java
  src/main/java/com/jane_eno/issue_tracker/service/MilestoneService.java
  src/main/java/com/jane_eno/issue_tracker/web/LabelController.java
  src/main/java/com/jane_eno/issue_tracker/web/MilestoneController.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/LabelsToUpdateRequestDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/MilestonesToUpdateRequestDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/CommentDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueDetailPageResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueFormResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/LabelDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/LabelsInIssueResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/LabelsResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/MilestoneDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/MilestonesInIssueResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/MilestonesResponseDTO.java
Labels: BE

#32 [BE] 이슈 생성 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/jane_eno/issue_tracker/auth/util/JwtUtil.java
  src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
  src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
  src/main/java/com/jane_eno/issue_tracker/domain/issue/IssueRepository.java
  src/main/java/com/jane_eno/issue_tracker/domain/label/Label.java
  src/main/java/com/jane_eno/issue_tracker/domain/label/LabelRepository.java
  src/main/java/com/jane_eno/issue_tracker/domain/milestone/Milestone.java
  src/main/java/com/jane_eno/issue_tracker/domain/user/User.java
  src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
  src/main/java/com/jane_eno/issue_tracker/service/LabelService.java
  src/main/java/com/jane_eno/issue_tracker/service/MilestoneService.java
  src/main/java/com/jane_eno/issue_tracker/service/UserService.java
  src/main/java/com/jane_eno/issue_tracker/web/IssueController.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/IssueNumbersRequestDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/IssueRequestDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/Assignee.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/LabelDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/MilestoneDTO.java
Labels: BE

#36 [BE] 이슈, 라벨, 마일스톤 관련 기본 기능 구현
  src/main/java/com/jane_eno/issue_tracker/auth/util/JwtUtil.java
  src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
  src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
  src/main/java/com/jane_eno/issue_tracker/domain/issue/IssueRepository.java
  src/main/java/com/jane_eno/issue_tracker/domain/label/Label.java
  src/main/java/com/jane_eno/issue_tracker/domain/label/LabelRepository.java
  src/main/java/com/jane_eno/issue_tracker/domain/milestone/Milestone.java
  src/main/java/com/jane_eno/issue_tracker/domain/user/User.java
  src/main/java/com/jane_eno/issue_tracker/exception/InvalidSearchRequestException.java
  src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
  src/main/java/com/jane_eno/issue_tracker/service/LabelService.java
  src/main/java/com/jane_eno/issue_tracker/service/MilestoneService.java
  src/main/java/com/jane_eno/issue_tracker/service/UserService.java
  src/main/java/com/jane_eno/issue_tracker/web/IssueController.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/AssigneesToUpdateRequestDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/IssueRequestDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/IssueTitleDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/LabelsToUpdateRequestDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/MilestoneToUpdateRequestDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/Assignee.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/AssigneesResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/CommentDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueDetailPageResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssuesResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/LabelDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/MilestoneDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/MilestonesInIssueResponseDTO.java
  src/main/java/com/jane_eno/issue_tracker/web/dto/response/MilestonesResponseDTO.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: BE

#38 [BE] 불필요한 import문 삭제 및 코드 정렬
  BE/src/main/java/com/jane_eno/issue_tracker/IssueTrackerApplication.java
  BE/src/main/java/com/jane_eno/issue_tracker/auth/exception/GitHubUserNotFoundException.java
  BE/src/main/java/com/jane_eno/issue_tracker/auth/exception/HttpProtocolViolationException.java
  BE/src/main/java/com/jane_eno/issue_tracker/auth/exception/OAuthException.java
  BE/src/main/java/com/jane_eno/issue_tracker/auth/exception/UnknownUserAgentException.java
  BE/src/main/java/com/jane_eno/issue_tracker/auth/util/GitHubUtil.java
  BE/src/main/java/com/jane_eno/issue_tracker/auth/util/JwtUtil.java
  BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
  BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
  BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/IssueRepository.java
  BE/src/main/java/com/jane_eno/issue_tracker/domain/label/Color.java
  BE/src/main/java/com/jane_eno/issue_tracker/domain/label/Label.java
  BE/src/main/java/com/jane_eno/issue_tracker/domain/label/LabelRepository.java
  BE/src/main/java/com/jane_eno/issue_tracker/domain/milestone/Milestone.java
  BE/src/main/java/com/jane_eno/issue_tracker/domain/user/User.java
  BE/src/main/java/com/jane_eno/issue_tracker/exception/InvalidSearchRequestException.java
  BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
  BE/src/main/java/com/jane_eno/issue_tracker/service/MilestoneService.java
  BE/src/main/java/com/jane_eno/issue_tracker/service/UserService.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/AssigneesToUpdateRequestDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/IssueRequestDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/LabelsToUpdateRequestDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/AssigneesResponseDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueDetailPageResponseDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueFormResponseDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssueResponseDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/IssuesResponseDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/LabelsResponseDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/MilestonesInIssueResponseDTO.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/vo/Assignee.java
  BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/vo/Count.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
Labels: BE

#39 [FE] 메인페이지, 로그인페이지 마크업 및 리팩토링
  .vscode/settings.json
  frontend/.env
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/miles.png
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/atom/CheckBox.tsx
  frontend/src/components/atom/LabelBadge.tsx
  frontend/src/components/atom/LableList.tsx
  frontend/src/components/atom/List.tsx
  frontend/src/components/atom/MilestoneIcon.tsx
  frontend/src/components/atom/PrimaryButton.tsx
  frontend/src/components/atom/RadioBtn.tsx
  frontend/src/components/common/Copyright.tsx
  frontend/src/components/common/LabelMilestoneTab.tsx
  frontend/src/components/common/LabelSelectItem.tsx
  frontend/src/components/common/MilestoneSelectItem.tsx
  frontend/src/components/common/UserSelectItem.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/hooks/useToggle.tsx
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/page/loginPage/LoginPage.tsx
  frontend/src/page/loginPage/loginForm/LoginForm.tsx
  frontend/src/page/loginPage/loginLogo/LoginLogo.tsx
  frontend/src/page/loginPage/socialLoginBtn/SocialLoginBtn.tsx
  frontend/src/page/mainPage/MainPage.tsx
  frontend/src/page/mainPage/issueTable/IssueItem.tsx
  frontend/src/page/mainPage/issueTable/IssueTable.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeader.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeaderLeft.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeaderRight.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/IssueTableFilterModal.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/ModalContentList.tsx
  frontend/src/page/mainPage/issueTable/issueType.tsx
  frontend/src/page/mainPage/optionTable/OptionTable.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilter.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterBtn.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterModal.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/SearchInput.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/store/issueInfoStore.ts
  frontend/src/style/Theme.tsx
  frontend/src/util/util.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: FE, enhancement

#43 style: (#42) issue modal : assignee markup
  frontend/src/components/common/UserSelectItem.tsx
  frontend/src/index.css
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/IssueTableFilterModal.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/ModalContentList.tsx
  frontend/src/page/writePage/WritePage.tsx
  frontend/src/style/Theme.tsx
Labels: FE, style

#44 [FE] 모달창 라벨,마일스톤 selectItem 스타일
  frontend/src/components/common/LabelSelectItem.tsx
  frontend/src/components/common/MilestoneSelectItem.tsx
  frontend/src/index.css
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/IssueTableFilterModal.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/ModalContentList.tsx
  frontend/src/style/Theme.tsx
Labels: FE, style

#51 이슈생성페이지 마크업 및 Reat.lazy 적용
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/atom/ProfileImg.tsx
  frontend/src/components/atom/Title.tsx
  frontend/src/components/common/UserSelectItem.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/page/createIssuePage/CreateIssuePage.tsx
  frontend/src/page/createIssuePage/issueDetailOption/IssueDetailOption.tsx
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/mainPage/MainPage.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeader.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeaderRight.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/IssueTableFilterModal.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/issueTableFilterModal/ModalContentList.tsx
  frontend/src/page/mainPage/optionTable/OptionTable.tsx
  frontend/src/page/writePage/WritePage.tsx
  frontend/src/style/Theme.tsx
  frontend/yarn.lock
Labels: FE, enhancement, style

#52 [BE] 3차 코드 리뷰 반영
  BE/src/main/java/com/issuetracker/auth/GitHubOAuth.java
  BE/src/main/java/com/issuetracker/auth/OAuth.java
  BE/src/main/java/com/issuetracker/auth/dto/UserAgentDTO.java
  BE/src/main/java/com/issuetracker/auth/dto/UserResponseDTO.java
  BE/src/main/java/com/issuetracker/domain/user/User.java
  BE/src/main/java/com/issuetracker/exception/ElementNotFoundException.java
  BE/src/main/java/com/issuetracker/service/UserService.java
  BE/src/main/java/com/issuetracker/web/UserController.java
Labels: BE

#55 chore. 불필요한 코드 및 모듈 삭제
  frontend/package.json
  frontend/src/App.js
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/mainPage/MainPage.tsx
  frontend/yarn.lock
Labels: FE

#66 [BE] S3 버켓 이미지 업로드 기능 구현
  BE/build.gradle
  BE/src/main/java/com/issuetracker/auth/GitHubOAuth.java
  BE/src/main/java/com/issuetracker/auth/dto/OAuthUserResponseDTO.java
  BE/src/main/java/com/issuetracker/config/QueryDSLConfig.java
  BE/src/main/java/com/issuetracker/config/UserAgentHeaderConverter.java
  BE/src/main/java/com/issuetracker/domain/image/Image.java
  BE/src/main/java/com/issuetracker/domain/image/ImageRepository.java
  BE/src/main/java/com/issuetracker/domain/issue/CustomizedIssueRepository.java
  BE/src/main/java/com/issuetracker/domain/issue/CustomizedIssueRepositoryImpl.java
  BE/src/main/java/com/issuetracker/domain/user/UserRepository.java
  BE/src/main/java/com/issuetracker/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/issuetracker/service/ImageService.java
  BE/src/main/java/com/issuetracker/service/IssueService.java
  BE/src/main/java/com/issuetracker/service/UserService.java
  BE/src/main/java/com/issuetracker/web/ImageController.java
  BE/src/main/java/com/issuetracker/web/IssueController.java
  BE/src/main/java/com/issuetracker/web/UserController.java
  BE/src/main/java/com/issuetracker/web/dto/reqeust/SearchRequestDTO.java
  BE/src/main/java/com/issuetracker/web/dto/response/AuthorsResponseDTO.java
  BE/src/main/java/com/issuetracker/web/dto/response/IssueNumberResponseDTO.java
  BE/src/main/java/com/issuetracker/web/dto/vo/Assignee.java
  BE/src/main/java/com/issuetracker/web/dto/vo/Author.java
  BE/src/main/java/com/issuetracker/web/dto/vo/Count.java
  BE/src/main/java/com/issuetracker/web/dto/vo/SearchRequest.java
  BE/src/main/java/com/issuetracker/web/dto/vo/Status.java
Labels: BE

#69 이슈생성요청_Fe/feature/issue create
  frontend/src/components/atom/PrimaryButton.tsx
  frontend/src/components/common/tabModal/LabelSelectItem.tsx
  frontend/src/components/common/tabModal/MilestoneSelectItem.tsx
  frontend/src/components/common/tabModal/ModalContentList.tsx
  frontend/src/components/common/tabModal/TabModal.tsx
  frontend/src/components/common/tabModal/UserSelectItem.tsx
  frontend/src/components/common/tabModal/tapDataType.ts
  frontend/src/page/createIssuePage/CreateIssuePage.tsx
  frontend/src/page/createIssuePage/issueDetailOption/IssueDetailOption.tsx
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeaderRight.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterModal.tsx
  frontend/src/store/issueInfoStore.ts
  frontend/src/style/Theme.tsx
  frontend/src/util/api/api.ts
  frontend/src/util/api/apiType.ts
Labels: FE, enhancement

#71 detailpage : Fe/feature/create merge
  frontend/src/App.js
  frontend/src/assets/icon/RadioButton.svg
  frontend/src/components/atom/LabelBadge.tsx
  frontend/src/components/atom/ProfileImg.tsx
  frontend/src/components/common/tabModal/LabelSelectItem.tsx
  frontend/src/components/common/tabModal/MilestoneSelectItem.tsx
  frontend/src/components/common/tabModal/ModalContentList.tsx
  frontend/src/components/common/tabModal/TabModal.tsx
  frontend/src/components/common/tabModal/UserSelectItem.tsx
  frontend/src/page/createIssuePage/CreateIssuePage.tsx
  frontend/src/page/createIssuePage/issueDetailOption/IssueDetailOption.tsx
  frontend/src/page/createIssuePage/issueDetailOption/SelectedTabLabel.tsx
  frontend/src/page/createIssuePage/issueDetailOption/SelectedTabMilestone.tsx
  frontend/src/page/createIssuePage/issueDetailOption/SelectedTabUser.tsx
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/store/issueInfoStore.ts
Labels: FE, enhancement

#72 [BE] JASYPT 적용
  BE/build.gradle
  BE/src/main/java/com/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/com/issuetracker/config/JasyptConfig.java
  BE/src/main/java/com/issuetracker/domain/issue/Issue.java
  BE/src/main/java/com/issuetracker/service/IssueService.java
  BE/src/main/java/com/issuetracker/web/IssueController.java
  BE/src/main/resources/application-auth.properties
  BE/src/main/resources/application-prod.properties
  BE/src/main/resources/application.properties
Labels: BE

#79 [BE] 헤더 검증 방식 변경, 예외 추가, IssueService 분리
  BE/src/main/java/com/issuetracker/auth/GitHubOAuth.java
  BE/src/main/java/com/issuetracker/auth/OAuth.java
  BE/src/main/java/com/issuetracker/auth/dto/HostDTO.java
  BE/src/main/java/com/issuetracker/auth/dto/UserAgentDTO.java
  BE/src/main/java/com/issuetracker/auth/exception/InvalidGitHubRequestException.java
  BE/src/main/java/com/issuetracker/auth/exception/UnknownHostException.java
  BE/src/main/java/com/issuetracker/auth/service/GitHubService.java
  BE/src/main/java/com/issuetracker/auth/service/Host.java
  BE/src/main/java/com/issuetracker/auth/service/UserAgent.java
  BE/src/main/java/com/issuetracker/config/HostHeaderConverter.java
  BE/src/main/java/com/issuetracker/config/UserAgentHeaderConverter.java
  BE/src/main/java/com/issuetracker/domain/issue/Issue.java
  BE/src/main/java/com/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/com/issuetracker/exception/CommentNotFoundException.java
  BE/src/main/java/com/issuetracker/exception/ElementNotFoundException.java
  BE/src/main/java/com/issuetracker/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/issuetracker/exception/IssueNotFoundException.java
  BE/src/main/java/com/issuetracker/exception/LabelNotFoundException.java
  BE/src/main/java/com/issuetracker/exception/MilestoneNotFoundException.java
  BE/src/main/java/com/issuetracker/exception/UserNotFoundException.java
  BE/src/main/java/com/issuetracker/service/ImageService.java
  BE/src/main/java/com/issuetracker/service/IssueCommandService.java
  BE/src/main/java/com/issuetracker/service/IssueQueryService.java
  BE/src/main/java/com/issuetracker/service/LabelService.java
  BE/src/main/java/com/issuetracker/service/MilestoneService.java
  BE/src/main/java/com/issuetracker/service/UserService.java
  BE/src/main/java/com/issuetracker/web/IssueController.java
  BE/src/main/java/com/issuetracker/web/UserController.java
  BE/src/main/java/com/issuetracker/web/dto/response/IssueDetailPageResponseDTO.java
  BE/src/main/java/com/issuetracker/web/dto/response/LabelDTO.java
  BE/src/main/java/com/issuetracker/web/dto/response/MilestoneDTO.java
  BE/src/main/java/com/issuetracker/web/dto/response/MilestonesInIssueResponseDTO.java
  BE/src/main/java/com/issuetracker/web/dto/vo/Assignee.java
  BE/src/main/resources/application-prod.properties
Labels: BE

#81 [FE] 로그인, 이슈 생성, 리팩토링
  frontend/.env
  frontend/src/App.js
  frontend/src/components/atom/PrimaryButton.tsx
  frontend/src/components/atom/ProfileImg.tsx
  frontend/src/components/atom/Progress.tsx
  frontend/src/components/common/LabelMilestoneTab.tsx
  frontend/src/components/common/tabModal/ModalContentList.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/hooks/useToggle.tsx
  frontend/src/index.css
  frontend/src/page/createIssuePage/CreateIssuePage.tsx
  frontend/src/page/createIssuePage/issueDetailOption/IssueDetailOption.tsx
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/lablePage/LablePage.tsx
  frontend/src/page/loginPage/LoginPage.tsx
  frontend/src/page/loginPage/socialLoginBtn/SocialLoginBtn.tsx
  frontend/src/page/mainPage/MainPage.tsx
  frontend/src/page/mainPage/issueTable/IssueItem.tsx
  frontend/src/page/mainPage/optionTable/OptionTable.tsx
  frontend/src/page/milestonePage/MilestonePage.tsx
  frontend/src/store/issueInfoStore.ts
  frontend/src/store/loginStore.ts
  frontend/src/util/api/api.ts
  frontend/src/util/api/fetchCreate.ts
  frontend/src/util/api/fetchLogin.ts
Labels: FE, enhancement, refactor, style

#83 [FE] 디테일 페이지 마크업
  frontend/src/assets/icon/EditIcons.svg
  frontend/src/assets/icon/Emoji.svg
  frontend/src/assets/icon/IssueDeleteBtn.svg
  frontend/src/assets/icon/LabelLargeClose.svg
  frontend/src/assets/icon/LabelLargeOpen.svg
  frontend/src/components/common/tabModal/tapDataType.ts
  frontend/src/components/header/Header.tsx
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/page/detailIssuePage/commentList/Comment.tsx
  frontend/src/page/detailIssuePage/commentList/CommentInput.tsx
  frontend/src/page/detailIssuePage/commentList/CommentList.tsx
  frontend/src/page/detailIssuePage/detailHeader/DetailIssueHeader.tsx
  frontend/src/page/detailIssuePage/detailHeader/DetailIssueStatus.tsx
  frontend/src/util/util.ts
Labels: FE, style

#89 로그인 로직 변경 / 마일스톤 페이지 작업 중
  frontend/.env
  frontend/src/App.js
  frontend/src/components/header/Header.tsx
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/loginPage/LoginPage.tsx
  frontend/src/page/mainPage/MainPage.tsx
  frontend/src/page/milestonePage/MilestoneAdd.tsx
  frontend/src/page/milestonePage/MilestonePage.tsx
  frontend/src/store/issueInfoStore.ts
  frontend/src/store/labelMilestoneStore.ts
  frontend/src/store/loginStore.ts
  frontend/src/util/api/api.ts
Labels: FE, refactor

#93 [BE] 마일스톤 열기 or 닫기 API 생성
  BE/src/main/java/com/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/com/issuetracker/domain/milestone/MilestoneRepository.java
  BE/src/main/java/com/issuetracker/exception/InvalidSearchRequestException.java
  BE/src/main/java/com/issuetracker/service/IssueQueryService.java
  BE/src/main/java/com/issuetracker/service/MilestoneService.java
  BE/src/main/java/com/issuetracker/web/MilestoneController.java
  BE/src/main/java/com/issuetracker/web/dto/reqeust/MilestoneNumbersRequestDTO.java
  BE/src/main/java/com/issuetracker/web/dto/response/MilestoneDTO.java
  BE/src/main/java/com/issuetracker/web/dto/response/MilestonesResponseDTO.java
  BE/src/main/resources/data.sql
Labels: BE

#91 로그인 수정/ 마일스톤 api
  frontend/.env
  frontend/src/App.js
  frontend/src/components/header/Header.tsx
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/loginPage/LoginPage.tsx
  frontend/src/page/loginPage/socialLoginBtn/SocialLoginBtn.tsx
  frontend/src/page/mainPage/MainPage.tsx
  frontend/src/page/milestonePage/MilestoneAdd.tsx
  frontend/src/page/milestonePage/MilestonePage.tsx
  frontend/src/store/issueInfoStore.ts
  frontend/src/store/labelMilestoneStore.ts
  frontend/src/store/loginStore.ts
  frontend/src/util/api/api.ts
Labels: FE, refactor

#94 로그인 드디어 완!료! : )
  frontend/src/App.js
  frontend/src/components/common/tabModal/tapDataType.ts
  frontend/src/components/header/Header.tsx
  frontend/src/page/loginPage/LoginPage.tsx
  frontend/src/page/milestonePage/MilestoneAdd.tsx
  frontend/src/page/milestonePage/MilestonePage.tsx
  frontend/src/store/loginStore.ts
  frontend/src/util/api/api.ts
Labels: FE, enhancement

#99 Detail page title
  frontend/src/App.js
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/page/detailIssuePage/commentList/CommentList.tsx
  frontend/src/page/detailIssuePage/detailHeader/DetailIssueHeader.tsx
  frontend/src/page/detailIssuePage/detailHeader/HeaderEditMode.tsx
  frontend/src/page/detailIssuePage/detailHeader/HeaderViewMode.tsx
  frontend/src/page/detailIssuePage/detailType.ts
  frontend/src/page/mainPage/issueTable/IssueItem.tsx
  frontend/src/store/detailStore.ts
  frontend/src/store/issueInfoStore.ts
  frontend/src/util/api/api.ts
  frontend/src/util/api/fetchEditTitle.ts
Labels: FE

#100 [FE] 디테일 페이지 fetch 요청 및 리팩토링
  frontend/src/App.js
  frontend/src/components/common/tabModal/tapDataType.ts
  frontend/src/components/header/Header.tsx
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/page/detailIssuePage/detailHeader/DetailIssueHeader.tsx
  frontend/src/page/detailIssuePage/detailHeader/HeaderEditMode.tsx
  frontend/src/page/detailIssuePage/detailHeader/HeaderViewMode.tsx
  frontend/src/page/loginPage/LoginPage.tsx
  frontend/src/page/mainPage/issueTable/IssueItem.tsx
  frontend/src/page/milestonePage/MilestonePage.tsx
  frontend/src/store/detailStore.ts
  frontend/src/store/issueInfoStore.ts
  frontend/src/store/loginStore.ts
  frontend/src/util/api/api.ts
  frontend/src/util/api/fetchIssueDetail.ts
Labels: FE, enhancement, refactor

#102 [FE]라벨페이지 관련 기능 구현 완료
  frontend/src/assets/icon/RefreshIcon.svg
  frontend/src/components/atom/InputField.tsx
  frontend/src/components/atom/LabelBadge.tsx
  frontend/src/components/common/LabelMilestoneTab.tsx
  frontend/src/hooks/useInput.tsx
  frontend/src/page/labelPage/LabelItem.tsx
  frontend/src/page/labelPage/LabelPage.tsx
  frontend/src/page/labelPage/labelEditForm/LabelEdit.tsx
  frontend/src/page/labelPage/labelEditForm/LabelEditForm.tsx
  frontend/src/page/labelPage/labelPageHeader/LabelPageHeader.tsx
  frontend/src/page/labelPage/labelTable/LabelItem.tsx
  frontend/src/page/labelPage/labelTable/LabelTable.tsx
  frontend/src/store/labelStore.ts
  frontend/src/style/Theme.tsx
  frontend/src/util/api/api.ts
  frontend/src/util/api/fetchLabel.ts
  frontend/src/util/randomColorUtil.ts
  frontend/src/util/util.ts
Labels: FE, enhancement, style

#103 [BE] Elastic Search 적용
  BE/build.gradle
  BE/src/main/java/com/issuetracker/auth/dto/HostDTO.java
  BE/src/main/java/com/issuetracker/domain/comment/Comment.java
  BE/src/main/java/com/issuetracker/domain/elasticsearch/CommentDocument.java
  BE/src/main/java/com/issuetracker/domain/elasticsearch/IssueDocument.java
  BE/src/main/java/com/issuetracker/domain/elasticsearch/IssueDocumentRepository.java
  BE/src/main/java/com/issuetracker/domain/elasticsearch/LabelDocument.java
  BE/src/main/java/com/issuetracker/domain/elasticsearch/MilestoneDocument.java
  BE/src/main/java/com/issuetracker/domain/elasticsearch/UserDocument.java
  BE/src/main/java/com/issuetracker/domain/issue/CustomizedIssueRepository.java
  BE/src/main/java/com/issuetracker/domain/issue/CustomizedIssueRepositoryImpl.java
  BE/src/main/java/com/issuetracker/domain/issue/Issue.java
  BE/src/main/java/com/issuetracker/domain/issue/IssueRepository.java
  BE/src/main/java/com/issuetracker/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/issuetracker/exception/IllegalUserAccessException.java
  BE/src/main/java/com/issuetracker/service/IssueCommandService.java
  BE/src/main/java/com/issuetracker/service/IssueQueryService.java
  BE/src/main/java/com/issuetracker/service/LabelService.java
  BE/src/main/java/com/issuetracker/service/MilestoneService.java
  BE/src/main/java/com/issuetracker/service/UserService.java
  BE/src/main/java/com/issuetracker/web/IssueController.java
  BE/src/main/java/com/issuetracker/web/dto/reqeust/FilterRequestDTO.java
  BE/src/main/java/com/issuetracker/web/dto/reqeust/MilestoneToUpdateRequestDTO.java
  BE/src/main/java/com/issuetracker/web/dto/reqeust/SearchRequestDTO.java
  BE/src/main/java/com/issuetracker/web/dto/response/IssueResponseDTO.java
  BE/src/main/java/com/issuetracker/web/dto/response/LabelDTO.java
  BE/src/main/java/com/issuetracker/web/dto/vo/Assignee.java
Labels: BE

#107 [FE] 리뷰 기반 리팩토링
  frontend/src/components/atom/Progress.tsx
  frontend/src/components/common/LabelMilestoneTab.tsx
  frontend/src/page/createIssuePage/CreateIssuePage.tsx
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/page/detailIssuePage/commentList/Comment.tsx
  frontend/src/page/detailIssuePage/detailHeader/DetailIssueHeader.tsx
  frontend/src/page/labelPage/labelEditForm/LabelEdit.tsx
  frontend/src/page/labelPage/labelEditForm/LabelEditForm.tsx
  frontend/src/page/loginPage/LoginPage.tsx
  frontend/src/page/mainPage/issueTable/IssueItem.tsx
  frontend/src/store/issueInfoStore.ts
  frontend/src/util/api/fetchCreateIssue.ts
  frontend/src/util/timeUtil.ts
Labels: refactor

#109 [FE] 디테일 페이지 옵션 부부 완성
  frontend/src/components/common/tabModal/ModalContentList.tsx
  frontend/src/components/common/tabModal/TabModal.tsx
  frontend/src/page/createIssuePage/issueDetailOption/IssueDetailOption.tsx
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/page/detailIssuePage/detailHeader/DetailIssueHeader.tsx
  frontend/src/page/detailIssuePage/detailIssueOption/DetailIssueOption.tsx
  frontend/src/page/detailIssuePage/detailIssueOption/OptionItem.tsx
  frontend/src/page/mainPage/issueTable/issueTableHeader/IssueTableHeaderRight.tsx
  frontend/src/page/mainPage/optionTable/issueFilter/IssueFilterModal.tsx
  frontend/src/store/detailStore.ts
  frontend/src/store/issueInfoStore.ts
  frontend/src/util/api/api.ts
  frontend/src/util/api/fetchEditTitle.ts
  frontend/src/util/api/fetchIssueDetail.ts
Labels: FE, enhancement

#110 [FE][FiX] 마일스톤 patch데이터 수정
  frontend/src/page/detailIssuePage/detailIssueOption/DetailIssueOption.tsx
  frontend/src/util/api/fetchIssueDetail.ts
Labels: FE, bug

#111 [FE] 리팩토링, 마일스톤페이지, 로그인 리다이렉션
  frontend/.env
  frontend/src/App.js
  frontend/src/components/atom/Progress.tsx
  frontend/src/components/common/tabModal/tapDataType.ts
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/loginPage/socialLoginBtn/SocialLoginBtn.tsx
  frontend/src/page/milestonePage/MilestoneAdd.tsx
  frontend/src/page/milestonePage/MilestoneInfo.tsx
  frontend/src/page/milestonePage/MilestoneInput.tsx
  frontend/src/page/milestonePage/MilestoneItem.tsx
  frontend/src/page/milestonePage/MilestonePage.tsx
  frontend/src/store/labelMilestoneStore.ts
  frontend/src/store/labelStore.ts
  frontend/src/util/api/api.ts
  frontend/src/util/api/fetchCreateIssue.ts
  frontend/src/util/api/fetchHandleMilestone.ts
Labels: FE, enhancement, style

#112 [FE][Fix] 메인페이지 이슈 리렌더링 이슈 해결
  frontend/src/components/header/Header.tsx
  frontend/src/store/issueInfoStore.ts
Labels: FE, bug

#115 [FE] 이슈 상세페이지 코멘트 관련 기능 구현
  frontend/src/components/common/tabModal/tapDataType.ts
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/page/detailIssuePage/commentList/Comment.tsx
  frontend/src/page/detailIssuePage/commentList/CommentInput.tsx
  frontend/src/page/detailIssuePage/commentList/CommentList.tsx
  frontend/src/page/detailIssuePage/commentList/EditComment.tsx
  frontend/src/page/loginPage/socialLoginBtn/SocialLoginBtn.tsx
  frontend/src/store/detailStore.ts
  frontend/src/util/api/api.ts
  frontend/src/util/api/fetchIssueDetail.ts
Labels: FE, enhancement, refactor

#118 주 변경사항: 프리티어 및 API/마일스톤 구조변경/최적화 Memo적용
  frontend/.env
  frontend/src/App.js
  frontend/src/components/atom/InputField.tsx
  frontend/src/components/atom/LabelBadge.tsx
  frontend/src/components/atom/PrimaryButton.tsx
  frontend/src/components/atom/PrimaryOutlinedButton.tsx
  frontend/src/components/atom/ProfileImg.tsx
  frontend/src/components/atom/Title.tsx
  frontend/src/components/common/LabelMilestoneTab.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/page/createIssuePage/CreateIssuePage.tsx
  frontend/src/page/createIssuePage/issueDetailOption/IssueDetailOption.tsx
  frontend/src/page/createIssuePage/issueInput/IssueInput.tsx
  frontend/src/page/detailIssuePage/DetailIssuePage.tsx
  frontend/src/page/detailIssuePage/detailIssueOption/DetailIssueOption.tsx
  frontend/src/page/detailIssuePage/detailIssueOption/OptionItem.tsx
  frontend/src/page/labelPage/labelEditForm/LabelEdit.tsx
  frontend/src/page/labelPage/labelEditForm/LabelEditForm.tsx
  frontend/src/page/labelPage/labelPageHeader/LabelPageHeader.tsx
  frontend/src/page/labelPage/labelTable/LabelTable.tsx
  frontend/src/page/mainPage/MainPage.tsx
  frontend/src/page/mainPage/issueTable/IssueItem.tsx
  frontend/src/page/milestonePage/MilestoneAdd.tsx
  frontend/src/page/milestonePage/MilestoneEditForm.tsx
  frontend/src/page/milestonePage/MilestoneInput.tsx
  frontend/src/page/milestonePage/MilestoneItem.tsx
  frontend/src/page/milestonePage/MilestonePage.tsx
  frontend/src/page/milestonePage/milestoneTable/MilestoneInfo.tsx
  frontend/src/page/milestonePage/milestoneTable/MilestoneItem.tsx
  frontend/src/page/milestonePage/milestoneTable/MilestoneTable.tsx
  frontend/src/store/issueInfoStore.ts
  frontend/src/store/labelMilestoneStore.ts
  frontend/src/util/api/api.ts
  frontend/src/util/api/apiType.ts
  frontend/src/util/api/fetchCreateIssue.ts
  frontend/src/util/api/fetchEditTitle.ts
  frontend/src/util/api/fetchHandleMilestone.ts
  frontend/src/util/api/fetchIssueDetail.ts
  frontend/src/util/api/fetchLabel.ts
  frontend/src/util/api/fetchLogin.ts
Labels: FE, enhancement, refactor
